name: shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  circle_flags: ^5.0.0
  cupertino_icons: ^1.0.6
  fan_carousel_image_slider: ^1.0.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  modal_progress_hud_nsn: ^0.5.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#42a5f5"
  image: assets\images\PngItem_3621616.png
  android: true
  ios: true
  web: true
  android_gravity: center # Positions the image at the center for Android
  ios_content_mode: scaleAspectFill # Scales the image to fill the screen for iOS
  web_image_mode: center


flutter:
  uses-material-design: true
  assets:
    - assets/images/Shop App.png