// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8XHSQwraGIhUxSW7BdlezNbolsSL8cO4',
    appId: '1:308167499584:web:12e17e8de3fdf79f0fa4a5',
    messagingSenderId: '308167499584',
    projectId: 'shop-c44ce',
    authDomain: 'shop-c44ce.firebaseapp.com',
    storageBucket: 'shop-c44ce.appspot.com',
    measurementId: 'G-B1XYBSMHKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4Ug3Mjkjekz2I4jxiIRMQ8cLvF6Q3E0',
    appId: '1:308167499584:android:ecd04220effc60d70fa4a5',
    messagingSenderId: '308167499584',
    projectId: 'shop-c44ce',
    storageBucket: 'shop-c44ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOPOc3tvF5rUIMzNUe66pBdS-JNISVZQ',
    appId: '1:308167499584:ios:231d781ae94f96e70fa4a5',
    messagingSenderId: '308167499584',
    projectId: 'shop-c44ce',
    storageBucket: 'shop-c44ce.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOPOc3tvF5rUIMzNUe66pBdS-JNISVZQ',
    appId: '1:308167499584:ios:231d781ae94f96e70fa4a5',
    messagingSenderId: '308167499584',
    projectId: 'shop-c44ce',
    storageBucket: 'shop-c44ce.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8XHSQwraGIhUxSW7BdlezNbolsSL8cO4',
    appId: '1:308167499584:web:8a074231a270a7b70fa4a5',
    messagingSenderId: '308167499584',
    projectId: 'shop-c44ce',
    authDomain: 'shop-c44ce.firebaseapp.com',
    storageBucket: 'shop-c44ce.appspot.com',
    measurementId: 'G-DXJC20M5ZD',
  );
}
